- id: '1745371361598'
  alias: Couch Zone Shock - Live
  description: Shock if person is detected in the 'couch' zone and enforcement is
    enabled
  triggers:
  - topic: frigate/couch/person/active
    payload: '1'
    trigger: mqtt
  conditions:
  - condition: state
    entity_id: input_boolean.couch_restricted
    state: 'on'
  - condition: state
    entity_id: input_boolean.shocked
    state: 'off'
  actions:
  - action: rest_command.pavlok_couch
    data: {}
  - target:
      entity_id: input_boolean.shocked
    action: input_boolean.turn_on
    data: {}
  - action: counter.increment
    data: {}
    target:
      entity_id: counter.couch_shocks
  - action: rest_command.habitica_lounge_negative
    data: {}
  - delay: 00:01:00
  - target:
      entity_id: input_boolean.shocked
    action: input_boolean.turn_off
    data: {}
  mode: single
- id: '1745496301073'
  alias: 6am light
  description: ''
  triggers:
  - trigger: time
    at: 06:00:00
  conditions: []
  actions:
  - action: script.open_blinds
    metadata: {}
    data: {}
  - action: script.lighting_route_by_time_now
    metadata: {}
    data: {}
  - action: script.tv_blind_up
    metadata: {}
    data: {}
  - action: script.tv_open_kiosk_browser
    metadata: {}
    data: {}
  mode: single
- id: '1745498028899'
  alias: natural light AM
  description: ''
  triggers:
  - trigger: time
    at: 08:00:00
  conditions: []
  actions:
  - if:
    - condition: zone
      entity_id: device_tracker.jamess_iphone
      zone: zone.home
    then:
    - action: script.lighting_route_by_time_now
      metadata: {}
      data: {}
  - action: script.open_shades
    metadata: {}
    data: {}
  mode: single
- id: '1745524278768'
  alias: entry switch
  description: ''
  triggers:
  - device_id: c91eb9c0edbfbf43cb3c741aa9be08c3
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - action: script.tv_blind_up
    metadata: {}
    data: {}
  - action: script.toggle_lights
    metadata: {}
    data: {}
  mode: single
- id: '1748993940939'
  alias: Bed Shock (Zone Enforcement - Toggle)
  description: Shock if person detected in 'bed' zone and enforcement is enabled
  triggers:
  - topic: frigate/bed/person/active
    payload: '1'
    trigger: mqtt
  conditions:
  - condition: state
    entity_id: input_boolean.bed_restricted
    state: 'on'
  - condition: state
    entity_id: input_boolean.shocked
    state: 'off'
  actions:
  - action: rest_command.pavlok_bed
    data: {}
  - target:
      entity_id: input_boolean.shocked
    action: input_boolean.turn_on
    data: {}
  - action: counter.increment
    data: {}
    target:
      entity_id: counter.bed_shocks
  - action: rest_command.habitica_lounge_negative
    data: {}
  - delay: 00:01:00
  - target:
      entity_id: input_boolean.shocked
    action: input_boolean.turn_off
    data: {}
  mode: single
- id: '1751665927285'
  alias: Voice Projector Toggle
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Turn off the projector
    - Turn on the projector
  conditions: []
  actions:
  - action: script.tv_blind_up
    metadata: {}
    data: {}
  mode: single
- id: '1751666407923'
  alias: Turn off all lights
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Turn off all lights
  conditions: []
  actions:
  - type: turn_off
    device_id: 6fb902227b74101e4af5536f96186399
    entity_id: e04ebd5eec14f3878290b1b44632a2e2
    domain: light
  - type: turn_off
    device_id: 96038e8d9a047a590f1e1f1124025501
    entity_id: 8fb2eac3e1093dec128ee800845e5c10
    domain: light
  - type: turn_off
    device_id: 2581b53e814160a40687ffd86ece1177
    entity_id: c45cfc79905a497483b7a94096774880
    domain: light
  - type: turn_off
    device_id: 33f35eabf1514c7128057474cd7af6e9
    entity_id: cdcc446a146bc107e100d3afb165a268
    domain: light
  - type: turn_off
    device_id: 3eb16c84994a1c44abaf06a41c403ede
    entity_id: 0e86f0e61ffdda3668ca1bea89f4b0e7
    domain: light
  mode: single
- id: '1751666470340'
  alias: Turn on all lights
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Turn on all lights
  conditions: []
  actions:
  - action: script.lighting_route_by_time_now
    metadata: {}
    data: {}
  mode: single
- id: '1753737643702'
  alias: Playlister Run
  description: ''
  triggers:
  - at: '22:00:00'
    trigger: time
  conditions:
  - condition: time
    weekday:
    - sun
  actions:
  - action: rest_command.playlister
  mode: single
- id: '1758667743254'
  alias: New automation
  description: ''
  triggers:
  - trigger: zone
    entity_id: device_tracker.jamess_iphone
    zone: zone.home
    event: leave
  - trigger: conversation
    command: Good night
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id:
      - bedroom
      - kitchen
      - living_room
      - office
      - track
  - action: script.tv_blind_up
    metadata: {}
    data: {}
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.away
  - action: script.govee_all_lights_off
    metadata: {}
    data: {}
  - type: turn_off
    device_id: 7d5fcd316152f4fca9a268615d7329a9
    entity_id: 0589d63ff48533409f7079333291644c
    domain: remote
  mode: single
- id: '1758667825052'
  alias: Arrive Home
  description: ''
  triggers:
  - trigger: zone
    entity_id: device_tracker.jamess_iphone
    zone: zone.home
    event: enter
  conditions: []
  actions:
  - action: script.lighting_route_by_time_now
    metadata: {}
    data: {}
  - action: script.tv_blind_up
    metadata: {}
    data: {}
  mode: single
- id: '1758755459668'
  alias: Check in Tag — Morning Briefing
  description: Scan tag → generate briefing
  triggers:
  - trigger: tag
    tag_id: 0f8580b4-fdeb-4e25-beb4-b14c2e858093
  actions:
  - action: script.good_morning_briefing
  mode: single
- id: '1758776873357'
  alias: Sunsetty
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: '1:00:00'
  conditions:
  - condition: device
    device_id: 5410341dd5c869866f1ea308a80d251d
    domain: device_tracker
    entity_id: 0d70eb782aa83094f5f5761a0a20a13a
    type: is_home
  actions:
  - action: script.lighting_route_by_time_now
    metadata: {}
    data: {}
  mode: single
- id: '1758777023027'
  alias: Wind Doownnnn
  description: ''
  triggers:
  - trigger: time
    at: '20:30:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  conditions:
  - condition: device
    device_id: 5410341dd5c869866f1ea308a80d251d
    domain: device_tracker
    entity_id: 0d70eb782aa83094f5f5761a0a20a13a
    type: is_home
  actions:
  - action: script.lighting_route_by_time_now
    metadata: {}
    data: {}
  mode: single
- id: '1759527316227'
  alias: Button - Play/Stop/Next by Time of Day
  triggers:
  - device_id: eafc3d157ffa983a7b7fc41f8b2ddd06
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
    id: single
  - device_id: eafc3d157ffa983a7b7fc41f8b2ddd06
    domain: zha
    type: remote_button_double_press
    subtype: button
    trigger: device
    id: double
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: double
      sequence:
      - data:
          entity_id: '{{ player }}'
        action: media_player.media_next_track
    - conditions:
      - condition: trigger
        id: single
      sequence:
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ states(player) in [''playing'',''paused''] }}'
          sequence:
          - data:
              entity_id: '{{ player }}'
            action: media_player.media_play_pause
        default:
        - choose:
          - conditions:
            - condition: time
              after: 06:00:00
              before: '14:00:00'
            sequence:
            - data: {}
              action: script.play_bossa_nova_living_room_playlist_shuffle
          - conditions:
            - condition: time
              after: '14:00:00'
            sequence:
            - data: {}
              action: script.play_home_playlist_living_room_playlist_shuffle
  mode: single
  variables:
    player: media_player.living_room
- id: '1759530393448'
  alias: DJ Lighting
  description: ''
  triggers:
  - trigger: tag
    tag_id: 1bd5d7e4-7307-4d90-870d-a41552392328
  conditions: []
  actions:
  - action: script.govee_party
    metadata: {}
    data: {}
  mode: single
- id: '1759538955396'
  alias: dj party reset
  description: ''
  triggers:
  - trigger: tag
    tag_id: c169c9df-ea94-48e8-b533-fd3a7d706a7d
  conditions: []
  actions:
  - action: script.lighting_route_by_time_now
    metadata: {}
    data: {}
  mode: single
- id: '1759806238818'
  alias: DJ Off
  description: ''
  triggers:
  - trigger: tag
    tag_id: c169c9df-ea94-48e8-b533-fd3a7d706a7d
  conditions: []
  actions:
  - action: script.lighting_route_by_time_now
    metadata: {}
    data: {}
  mode: single
- id: '1759809606458'
  alias: bedbuttonthings
  description: ''
  triggers:
  - device_id: e58d7882f45586de849429b440d9d651
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
    id: single
  - device_id: e58d7882f45586de849429b440d9d651
    domain: zha
    type: remote_button_double_press
    subtype: button
    trigger: device
    id: double
  - device_id: e58d7882f45586de849429b440d9d651
    domain: zha
    type: remote_button_long_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: double
      sequence:
      - action: script.toggle_lights
        metadata: {}
        data: {}
    - conditions:
      - condition: trigger
        id: single
      sequence:
      - action: script.lights_off
        metadata: {}
        data: {}
      - action: script.close_blinds
        metadata: {}
        data: {}
  mode: single
  variables:
    player: media_player.living_room
- id: '1761221436021'
  alias: whats the weather
  description: ''
  triggers:
  - trigger: conversation
    command: What's the weather
  conditions: []
  actions:
  - action: weather.get_forecasts
    metadata: {}
    data:
      type: daily
    target:
      entity_id: weather.kmdw
  mode: single
- id: '1763522537243'
  alias: Lights back on
  description: ''
  triggers:
  - trigger: time
    at: 07:00:00
  conditions: []
  actions:
  - if:
    - condition: zone
      entity_id: device_tracker.jamess_iphone
      zone: zone.home
    then:
    - action: script.lighting_route_by_time_now
      metadata: {}
      data: {}
  mode: single
- id: '1765172397828'
  alias: Good NIght
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Good Night
  conditions: []
  actions:
  - action: script.close_shades
    metadata: {}
    data: {}
  - action: script.close_shades
    metadata: {}
    data: {}
  - action: script.lights_off
    metadata: {}
    data: {}
  mode: single
